export { AppShell } from './AppShell'
export type { AppShellProps } from './types'
export { Sidebar } from './Sidebar'
export { TopBar } from './TopBar'
export { MobileNavigation } from './MobileNavigation'
export { Breadcrumb } from './Breadcrumb'
export { SearchBar } from './SearchBar'
export { NotificationDropdown } from './NotificationDropdown'
export { UserMenu } from './UserMenu'
export { RoleSwitcher } from './RoleSwitcher'
export { QuickActionButton } from './QuickActionButton'
export { PageHeader } from './PageHeader'
export { PageContainer } from './PageContainer'
export { EmptyState } from './EmptyState'
export { ErrorState } from './ErrorState'
export { LoadingSkeleton } from './LoadingSkeleton'
export { useBreadcrumbs } from './useBreadcrumbs'
export { useNavBadges } from './useNavBadges'
export type * from './types'

export { publicNavItems, publicStudentNavItem } from './nav/publicNav'
export { getStudentNavItems } from './nav/studentNav'
export { teacherNavItems } from './nav/teacherNav'
export { adminNavItems } from './nav/adminNav'
