export type {
  Academy,
  AcademySettings,
  AcademyMember,
  TeacherAcademy,
  Batch,
  BatchStudent,
  AcademyStatus,
  AcademyMemberRole,
  AcademyMemberStatus,
  TeacherEmploymentType,
  TeacherAcademyStatus,
  BatchStatus,
  BatchDifficulty,
  BatchStudentStatus,
  BatchEnrollmentType,
  CreateAcademyInput,
  CreateBatchInput,
  AddAcademyMemberInput,
  EnrollBatchStudentInput,
  StudentAssociation,
} from './models'

export {
  ACADEMY_MANAGEMENT_ROLES,
  ACADEMY_TEACHING_ROLES,
  ACADEMY_FINANCE_ROLES,
  ACADEMY_FRONT_DESK_ROLES,
  buildAcademyPermissionContext,
  canViewAcademy,
  canManageAcademy,
  canManageAcademyTeachers,
  canManageAcademyBatches,
  canManageAcademyFinance,
  canManageAcademyStudents,
  hasAcademyRouteAccess,
  formatAcademyMemberRole,
} from './permissions'

export type { AcademyPermissionContext, PlatformRole, FuturePlatformRole } from './permissions'
