export type {
  Competition,
  CompetitionEvent,
  CompetitionCategory,
  CompetitionDivision,
  CompetitionRegistration,
  CompetitionParticipant,
  CompetitionJudge,
  CompetitionScore,
  CompetitionResult,
  CompetitionCertificate,
  CompetitionRanking,
  CompetitionAnnouncement,
  CertificateSignatureData,
  CompetitionStatus,
  CompetitionFormat,
  CompetitionScope,
  CompetitionEventStatus,
  CompetitionAgeGroup,
  CompetitionStyleType,
  CompetitionCategoryStatus,
  CompetitionRegistrantType,
  CompetitionRegistrationStatus,
  CompetitionPaymentStatus,
  CompetitionParticipantStatus,
  CompetitionJudgeRole,
  CompetitionJudgeStatus,
  CompetitionScoreStatus,
  CompetitionResultStatus,
  CompetitionMedal,
  CompetitionCertificateType,
  CompetitionCertificateStatus,
  CompetitionRankingScope,
  CompetitionRankingSubjectType,
  CompetitionAnnouncementAudience,
  CompetitionAnnouncementStatus,
  CreateCompetitionInput,
  CreateCompetitionCategoryInput,
  CreateCompetitionRegistrationInput,
  CreateCompetitionParticipantInput,
  AssignCompetitionJudgeInput,
  SubmitCompetitionScoreInput,
  IssueCertificateInput,
  CreateRankingEntryInput,
} from './models'

export {
  COMPETITION_PUBLIC_STATUSES,
  COMPETITION_REGISTRATION_OPEN_STATUSES,
  buildCompetitionPermissionContext,
  canViewCompetition,
  canManageCompetition,
  canRegisterForCompetition,
  canRegisterStudents,
  canBulkRegister,
  canScoreCompetition,
  canApproveResults,
  canIssueCertificates,
  canViewRankings,
  canManageRankings,
  hasCompetitionRouteAccess,
  hasJudgeRouteAccess,
  hasOrganizerRouteAccess,
  inferRegistrantType,
  formatCompetitionStatus,
  formatRankingScope,
} from './permissions'

export type {
  PlatformRole,
  FuturePlatformRole,
  CompetitionActorRole,
  CompetitionPermissionContext,
} from './permissions'
