/** User-facing product language — Yogstra V2 Operating System positioning */
export const TERMS = {
  platformName: 'Yogstra',
  platformTagline: 'The Operating System for Yoga Academies, Teachers, Students and Competitions',
  enrollInProgram: 'Enroll in Program',
  bookTrial: 'Book Trial',
  viewProfile: 'View Profile',
  messageCoach: 'Message Coach',
  personalCoaching: 'Personal Coaching',
  trainingBatch: 'Training Batch',
  competitionCoaching: 'Competition Coaching',
  discoverCoaches: 'Discover Coaches',
  myPrograms: 'My Programs',
  enrollments: 'Enrollments',
  confirmEnrollment: 'Confirm Enrollment',
  getStarted: 'Get Started',
  applyAsCoach: 'Apply as Coach',
  registerAcademy: 'Register Academy',
  registerOrganizer: 'Register Organizer',
  learnYoga: 'Learn Yoga',
  becomeCoach: 'Become a Coach',
  runAcademy: 'Run a Yoga Academy',
  hostCompetitions: 'Host Yoga Competitions',
} as const
