export { CompetitionHomePage } from './CompetitionHomePage'
export { CompetitionDetailPage } from './CompetitionDetailPage'
export { CompetitionResultsPage } from './CompetitionResultsPage'
export { CompetitionRankingsPage } from './CompetitionRankingsPage'
export { CompetitionCertificatesPage } from './CompetitionCertificatesPage'
export { OrganizerDashboardPage as OrganizerHomePage } from './OrganizerDashboardPage'
export { JudgeDashboardPage as JudgeHomePage } from '../judge/JudgeDashboardPage'
