export { AcademyHomePage } from './AcademyHomePage'
export { AcademyTeachersPage } from './AcademyTeachersPage'
export { AcademyStudentsPage } from './AcademyStudentsPage'
export { AcademyBatchesPage } from './AcademyBatchesPage'
export { AcademyFinancePage } from './AcademyFinancePage'
export { AcademyMembersPage } from './AcademyMembersPage'
export { AcademySettingsPage } from './AcademySettingsPage'
